name: CI/CD - Wisecow

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.set-image.outputs.image }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/wisecow:${{ github.sha }}
          ${{ secrets.DOCKER_USERNAME }}/wisecow:latest

    - name: Set image output
      id: set-image
      run: echo "image=${{ secrets.DOCKER_USERNAME }}/wisecow:${{ github.sha }}" >> $GITHUB_OUTPUT

  deploy-to-minikube:
    needs: build-and-push
    runs-on: [self-hosted, minikube]
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Deploy to Minikube
      run: |
        kubectl create namespace wisecow --dry-run=client -o yaml | kubectl apply -f -
        kubectl apply -f wisecow-service.yaml -n wisecow
        kubectl apply -f wisecow-deployment.yaml -n wisecow
        kubectl -n wisecow set image deployment/wisecow wisecow=${{ needs.build-and-push.outputs.image }} --record
        kubectl -n wisecow rollout status deployment/wisecow --timeout=120s
